services:
  modsecurity:
    image: owasp/modsecurity-crs:3.3.4-nginx-alpine-202304160904
    container_name: modsecurity
    hostname:       modsecurity
    environment:
      METRICS_ALLOW_FROM: 0.0.0.0/0
      # ModSecurity ENV Variables https://hub.docker.com/r/owasp/modsecurity-crs
      MODSEC_AUDIT_ENGINE: RelevantOnly
      MODSEC_AUDIT_LOG: /var/log/modsecurity/audit/concurent.log
      MODSEC_AUDIT_LOG_FORMAT: JSON
      MODSEC_AUDIT_LOG_TYPE: Serial
      MODSEC_AUDIT_LOG_PARTS: ABIJDEFHZ
      MODSEC_AUDIT_STORAGE: /var/log/modsecurity/audit
    volumes:
      - type: bind
        source: ./configs/nginx/nginx.conf
        target:  /etc/nginx/templates/nginx.conf.template
        read_only: true
      - type: bind
        source: ./configs/nginx/conf.d/default.conf
        target:  /etc/nginx/templates/conf.d/default.conf.template
        read_only: true
      - type: bind
        source: ./configs/nginx/includes/location_common.conf
        target:  /etc/nginx/templates/includes/location_common.conf.template
        read_only: true
      - type: bind
        source: ./modules/ngx_http_vhost_traffic_status_module.so
        target:  /usr/lib/nginx/modules/ngx_http_vhost_traffic_status_module.so
        read_only: true
      - type: bind
        source: ./logs
        target:  /var/log/modsecurity/audit
        read_only: false
    networks: ["modsecurity"]
    ports:    ["80:80", "443:443"]

  telegraf:
    image: telegraf:1.24.4-alpine
    container_name: telegraf
    hostname:       telegraf
    environment:
      HOST_ETC:  /hostfs/etc
      HOST_PROC: /hostfs/proc
      HOST_SYS:  /hostfs/sys
      HOST_VAR:  /hostfs/var
      HOST_RUN:  /hostfs/run
      HOST_MOUNT_PREFIX: /hostfs
    volumes:
      - type: bind
        source: ./configs/telegraf/telegraf.conf
        target:  /etc/telegraf/telegraf.conf
        read_only: true
      - type: bind
        source: /var/run
        target: /hostfs/var/run
        read_only: true
    user: root
    entrypoint: /usr/bin/telegraf
    networks: ["modsecurity"]
    ports:    ["9273:9273"]

  graphite:
    image: graphiteapp/graphite-statsd:1.1.10-4
    container_name: graphite
    hostname:       graphite
    networks: ["modsecurity"]
    ports:
      - 8080:80
      - 2003-2004:2003-2004
      - 2023-2024:2023-2024
      - 8125:8125/udp
      - 8126:8126

networks:
  modsecurity:
    name:   modsecurity
    driver: bridge