filebeat.inputs:
  - type: log
    enabled: true
    fields_under_root: true
    ignore_older: 72h
    paths:
      - /var/log/modsecurity/concurent.log

output.kafka:
  hosts: ["kafka-modsecurity:9092"]
  topic: "modsecurity_audit"
  required_acks: 1
  max_message_bytes: 1000000
  retry.backoff: 30000
  enable: true

setup.kibana:
  enable: false
  
output.elasticsearch:
  enabled: false
  
output.logstash:
  enabled: false

output.console:
  enabled: false
  pretty:  true

monitoring.enabled: false
  
logging:
  #path: /proc/self/fd/1
  to_stderr: true
  level: info
  json: false
  metrics.enabled: false