# https://vector.dev/docs/reference/configuration/sinks/console/

sources:
  input_kafka_modsecurity:
    type: kafka
    bootstrap_servers: kafka-modsecurity:9092
    group_id: vector
    topics:
      - modsecurity_audit
    decoding:
      codec: json