# https://vector.dev/docs/reference/configuration/sinks/console/

sources:
  input_kafka_modsecurity:
    type: kafka
    bootstrap_servers: kafka-modsecurity:9092
    group_id: vector
    topics:
      - modsecurity_audit
    decoding:
      codec: json

transforms:
  transform_modsecurity_split:
    inputs: 
      - input_kafka_modsecurity
    type: remap
    drop_on_abort: true
    source: |-
      . = parse_json!(.message)

      .transaction.request.headers  = encode_json(.transaction.request.headers)
      .transaction.response.headers = encode_json(.transaction.response.headers)
      
      . = unnest!(.transaction.messages)

  transform_modsecurity_ecs:
    inputs: 
      - transform_modsecurity_split
    type: remap
    drop_on_abort: true
    source: |-
      .@timestamp_origin = del(.transaction.time_stamp)
      .source.ip = del(.transaction.client_ip)
      .host.id = del(.transaction.server_id)
      .source.port = del(.transaction.client_port)
      .destination.ip = del(.transaction.host_ip)
      .destination.port = del(.transaction.host_port)
      .event.id = del(.transaction.unique_id)
      .event.dataset = "modsecurity.audit"

      .http.version = del(.transaction.request.http_version)

      .http.request.method = del(.transaction.request.method)
      .http.request.url.path = del(.transaction.request.uri)
      .http.request.captured_headers  = del(.transaction.request.headers)

      .http.response.body.content = del(.transaction.response.body)
      .http.response.status_code = del(.transaction.response.http_code)
      .http.response.captured_headers = del(.transaction.response.headers)

      .service.name = del(.transaction.producer.modsecurity)
      .service.type = del(.transaction.producer.connector)
      .service.state = del(.transaction.producer.secrules_engine)
      .service.components = del(.transaction.producer.components)

      .message          = del(.transaction.messages.message)
      .rule.description = del(.transaction.messages.details.match)
      .rule.reference   = del(.transaction.messages.details.reference)
      .rule.id          = del(.transaction.messages.details.ruleId)
      .rule.file        = del(.transaction.messages.details.file)
      .object.key       = del(.transaction.messages.details.data)
      .event.severity   = del(.transaction.messages.details.severity)
      .rule.version     = del(.transaction.messages.details.ver)
      .rule.revision    = del(.transaction.messages.details.rev)
      .tags             = del(.transaction.messages.details.tags)
      .rule.maturity    = del(.transaction.messages.details.maturity)
      .rule.accuracy    = del(.transaction.messages.details.accuracy)

      del(.transaction)

sinks:
  output_console:
    type: console
    inputs:
      - "transform_modsecurity_ecs"
    encoding:
      codec: "json"